apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
--- 
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: myapp
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80

